### ISSUE TITLE
Completion only working for first parameter

### ISSUE THREAD

**Issue by datamaan** [s7anley/zsh-geeknote#2]
Parameter completion is working when I do

    gn edit --<TAB>

but not when I do

    gn edit --note "test" --<TAB>

Is it possible to make it work for all parameter positions?

**Comment by s7anley** [comment]
Hi @datamaan,

it's been a while since I wrote this code and I cannot say I will make it work immediately, but I will give it a try.

**Comment by s7anley** [comment]
@datamaan Fix is already in master, I will create pull request also for `oh-my-zsh`.

**Comment by saladpanda** [comment]
Awesome. Thank you very much for your work!
